Changes from production

diff --git a/give b/give
--- a/give
+++ b/give
@@ -1,5 +1,8 @@
 #!/bin/bash -i
 
+#echo "Give and Take is migrating due to Global Scratch Retirement. We'll be back soon"
+#exit 1
+
 # Clean and unset vars. We now also use -i above.
 giver=""
 user=""
@@ -13,20 +16,48 @@ current_dir=""
 PATH=""
 LD_LIBRARY_PATH=""
 unset IFS
+my_date=`/bin/date +%s`
 
 # Implementation Definitions
-SPOOLAREA=/global/scratch/gt
+#SPOOLAREA=/global/scratch2/gt
+SPOOLAREA=/project/projectdirs/gt
 
 # Get Giver's Name
 giver=`/usr/bin/whoami`
 
+# Get Hostname
+myhost=`/usr/common/usg/bin/nersc_host`
+#echo $myhost
+
+if [ "$myhost" == "genepool" ]; then
+  myreadlink="/bin/readlink"
+  mylogger="/usr/bin/logger"
+  mymail="/usr/bin/mail"
+else
+  myreadlink="/usr/bin/readlink"
+  mylogger="/bin/logger"
+  mymail="/bin/mail"
+fi
+
+# Make sure scratch is available and giver has directory
+if [ ! -d "$SPOOLAREA/$giver" ]; then
+  echo "$giver has no mounted give area"
+  exit 1
+fi
+
+
 # Catch odd directories
 current_dir=`/bin/pwd`
 
-while getopts ":u:" opt; do
+batchflag="no"
+
+while getopts ":u:b" opt; do
   case $opt in
     u)
       user="$OPTARG"
+      ;;
+    b)
+      batchflag="yes"
       ;;
     \?)
       echo ""
@@ -88,6 +119,11 @@ then
     fi
 
     my_var="$var"
+    if [ "$myhost" == "genepool" ]; then
+      my_short_var=`/usr/bin/basename "$var"`
+    else
+      my_short_var=`/bin/basename "$var"`
+    fi
 
 # Copy file over. Create .tar archive if directory.
 
@@ -100,67 +136,134 @@ then
       my_var=${var%/}.tar
       my_var=${my_var##*/}
       tmpdir=${var%/}
-      parentdir=`dirname "$tmpdir"`
+      parentdir=`/usr/bin/dirname "$tmpdir"`
       dir2tar=${tmpdir##*/}
       echo "Creating tar archive from directory $var"
-      /bin/cd "$parentdir"
-      tar -cvf "$SPOOLAREA/$giver/$user/$my_var" "$dir2tar"
-      if [ $? -eq 0 ] 
+      cd "$parentdir"
+      if [ -a "$SPOOLAREA/$giver/$user/$my_var" ] 
       then
-        messagebody="$messagebody \n $my_var"
-        /usr/bin/setfacl -R -d -m u:$user:rwx $SPOOLAREA/$giver/$user/$my_var
-        /usr/bin/setfacl -R -m u:$user:rw,g::---,m::rw $SPOOLAREA/$giver/$user/$my_var
-        echo "`/bin/date` - gave $user `/usr/bin/readlink -f $my_var`" >> ~/.filesgiven
-        /bin/logger "`/bin/date` - $giver gave $user `/usr/bin/readlink -f $my_var`"
-        echo "Gave $my_var."
-      else 
-        echo "Failed to give $my_var. Removing any incomplete files."
-        # Remove incomplete give
-        rm "$SPOOLAREA/$giver/$user/$my_var"
-      fi
-      cd "$current_dir"
-      echo " "
-# This is a file not a directory
-    else
-      if [ -a "$SPOOLAREA/$giver/$user/$var" ]
-      then
-        echo "File $var already exists at destination. Overwrite?"
-        select yn in "Yes" "No"; do
-          case $yn in
-            Yes ) 
-              /usr/bin/rsync --progress --log-format="Giving $var" "$var" "$SPOOLAREA/$giver/$user"
-              if [ $? -eq 0 ] 
-              then
-                messagebody="$messagebody \n $my_var" 
-                /usr/bin/setfacl -R -d -m u:$user:rwx "$SPOOLAREA/$giver/$user/$my_var"
-                /usr/bin/setfacl -R -m u:$user:rw,g::---,m::rw "$SPOOLAREA/$giver/$user/$my_var"
-                echo "`/bin/date` - gave $user `/usr/bin/readlink -f $var`" >> ~/.filesgiven
-                /bin/logger "`/bin/date` - $giver gave $user `/usr/bin/readlink -f $var`"
-                echo "Gave $var"
-              else 
-                echo "Failed to give $var. Removing incomplete file."
-                # Remove incomplete give
-                rm "$SPOOLAREA/$giver/$user/$my_var"
-              fi
-              echo " " 
-              break;;
-            No ) echo " " ; break;;
-          esac
-        done
+        if [ "$batchflag" == "no" ]
+        then
+          echo "File $my_var already exists at destination. Overwrite?"
+          select yn in "Yes" "No"; do
+            case $yn in
+              Yes ) 
+                /bin/tar -cvf "$SPOOLAREA/$giver/$user/$my_var" "$dir2tar"
+                if [ $? -eq 0 ] 
+                then
+                  messagebody="$messagebody \n $my_var"
+                  /usr/bin/setfacl -R -d -m u:$user:rwx "$SPOOLAREA/$giver/$user/$my_var"
+                  /usr/bin/setfacl -R -m u:$user:rw,g::---,m::rw "$SPOOLAREA/$giver/$user/$my_var"
+                  echo "`/bin/date` - gave $user `$myreadlink -f '$my_var'`" >> ~/.filesgiven
+                  $mylogger "`/bin/date` - giveandtake $giver gave $user `$myreadlink -f '$my_var'`"
+                  echo "Gave $my_var."
+                else 
+                  echo "Failed to give $my_var. Removing any incomplete files."
+                  # Remove incomplete give
+                  /bin/rm "$SPOOLAREA/$giver/$user/$my_var"
+                fi
+                break;;
+              No ) echo " " ; break;;
+            esac
+          done
+        else
+                my_var="${my_date}_${my_var}"
+                /bin/tar -cvf "$SPOOLAREA/$giver/$user/$my_var" "$dir2tar"
+                if [ $? -eq 0 ] 
+                then
+                  messagebody="$messagebody \n $my_var"
+                  /usr/bin/setfacl -R -d -m u:$user:rwx "$SPOOLAREA/$giver/$user/$my_var"
+                  /usr/bin/setfacl -R -m u:$user:rw,g::---,m::rw "$SPOOLAREA/$giver/$user/$my_var"
+                  echo "`/bin/date` - gave $user `$myreadlink -f '$my_var'`" >> ~/.filesgiven
+                  $mylogger "`/bin/date` - giveandtake $giver gave $user `$myreadlink -f '$my_var'`"
+                  echo "Gave $my_var."
+                else 
+                  echo "Failed to give $my_var. Removing any incomplete files."
+                  # Remove incomplete give
+                  /bin/rm "$SPOOLAREA/$giver/$user/$my_var"
+                fi
+        fi
       else
-        /usr/bin/rsync --progress --log-format="Giving $var" "$var" "$SPOOLAREA/$giver/$user"
+        /bin/tar -cvf "$SPOOLAREA/$giver/$user/$my_var" "$dir2tar"
         if [ $? -eq 0 ] 
         then
           messagebody="$messagebody \n $my_var"
           /usr/bin/setfacl -R -d -m u:$user:rwx "$SPOOLAREA/$giver/$user/$my_var"
           /usr/bin/setfacl -R -m u:$user:rw,g::---,m::rw "$SPOOLAREA/$giver/$user/$my_var"
+          echo "`/bin/date` - gave $user `$myreadlink -f '$my_var'`" >> ~/.filesgiven
+          $mylogger "`/bin/date` - giveandtake $giver gave $user `$myreadlink -f '$my_var'`"
+          echo "Gave $my_var."
+        else 
+          echo "Failed to give $my_var. Removing any incomplete files."
+          # Remove incomplete give
+          /bin/rm "$SPOOLAREA/$giver/$user/$my_var"
+        fi
+      fi
+      cd "$current_dir"
+      echo " "
+# This is a file not a directory
+    else
+      if [ -a "$SPOOLAREA/$giver/$user/$my_short_var" ]
+      then
+        if [ "$batchflag" == "no" ]
+        then
+          echo "File $var already exists at destination. Overwrite?"
+          select yn in "Yes" "No"; do
+            case $yn in
+              Yes ) 
+                /usr/bin/rsync --progress --log-format="Giving $my_short_var" "$var" "$SPOOLAREA/$giver/$user"
+                if [ $? -eq 0 ] 
+                then
+                  messagebody="$messagebody \n $my_short_var" 
+                  /usr/bin/setfacl -R -d -m u:$user:rwx "$SPOOLAREA/$giver/$user/$my_short_var"
+                  /usr/bin/setfacl -R -m u:$user:rw,g::---,m::rw "$SPOOLAREA/$giver/$user/$my_short_var"
+                  echo "`/bin/date` - gave $user `$myreadlink -f '$var'`" >> ~/.filesgiven
+                  $mylogger "`/bin/date` - giveandtake $giver gave $user `$myreadlink -f '$var'`"
+                  echo "Gave $var"
+                else 
+                  echo "Failed to give $var. Removing incomplete file."
+                  # Remove incomplete give
+                  rm "$SPOOLAREA/$giver/$user/$my_short_var"
+                fi
+                echo " " 
+                break;;
+              No ) echo " " ; break;;
+            esac
+          done
+        else
+                my_short_var="${my_date}_${my_short_var}"
+                /usr/bin/rsync --progress --log-format="Giving $my_short_var" "$var" "$SPOOLAREA/$giver/$user/$my_short_var"
+                if [ $? -eq 0 ] 
+                then
+                  messagebody="$messagebody \n $my_short_var" 
+                  /usr/bin/setfacl -R -d -m u:$user:rwx "$SPOOLAREA/$giver/$user/$my_short_var"
+                  /usr/bin/setfacl -R -m u:$user:rw,g::---,m::rw "$SPOOLAREA/$giver/$user/$my_short_var"
+                  echo "`/bin/date` - gave $user `$myreadlink -f '$var'`" >> ~/.filesgiven
+                  $mylogger "`/bin/date` - giveandtake $giver gave $user `$myreadlink -f '$var'`"
+                  echo "Gave $var"
+                else 
+                  echo "Failed to give $var. Removing incomplete file."
+                  # Remove incomplete give
+                  rm "$SPOOLAREA/$giver/$user/$my_short_var"
+                fi
+                echo " " 
+        fi
+      else
+        echo "About to give $var"
+        echo /usr/bin/rsync --progress --log-format="Giving $my_short_var" "$var" "$SPOOLAREA/$giver/$user"
+        /usr/bin/rsync --progress --log-format="Giving $my_short_var" "$var" "$SPOOLAREA/$giver/$user"
+        if [ $? -eq 0 ] 
+        then
+          messagebody="$messagebody \n $my_short_var"
+          /usr/bin/setfacl -R -d -m u:$user:rwx "$SPOOLAREA/$giver/$user/$my_short_var"
+          /usr/bin/setfacl -R -m u:$user:rw,g::---,m::rw "$SPOOLAREA/$giver/$user/$my_short_var"
           echo "Gave $var"
-          echo "`/bin/date` - gave $user `/usr/bin/readlink -f $var`" >> ~/.filesgiven
-          /bin/logger "`/bin/date` - $giver gave $user `/usr/bin/readlink -f $var`"
+          echo "`/bin/date` - gave $user `$myreadlink -f '$var'`" >> ~/.filesgiven
+          $mylogger "`/bin/date` - giveandtake $giver gave $user `/$myreadlink -f '$var'`"
         else 
           echo "Failed to give $var. Removing incomplete file."
           # Remove incomplete give
-          rm "$SPOOLAREA/$giver/$user/$my_var"
+          rm "$SPOOLAREA/$giver/$user/$my_short_var"
         fi
         echo " "
       fi
@@ -173,7 +276,7 @@ then
     echo "No files given"
   else
     messagebody="Shared Files: $messagebody"
-    messagebody="$messagebody \n\n Retrieve individual files using the take command (available only from the giveandtake module on Carver presently):"
+    messagebody="$messagebody \n\n Retrieve individual files using the take command and providing $giver as the username (-u) argument."
     # For security we no longer suggests users cut and paste from email
     #messagebody="$messagebody \n\n % take -u $giver <filename>"
     #messagebody="$messagebody \n\n Retrieve all files given by $giver using:"
@@ -185,8 +288,14 @@ then
     SUBJECT="$giver has given you a file at NERSC."
 # Email To ?
     EMAIL="$user@nersc.gov"
+# Email From ?
+    FROM="$giver@nersc.gov"
 # send an email using /bin/mail
-    echo -e "$messagebody" | /bin/mail -s "$SUBJECT" "$EMAIL"
+    if [ "$myhost" == "datatran" ]; then
+      echo -e "$messagebody" | $mymail -r "$FROM" -s "$SUBJECT" "$EMAIL"
+    else
+      echo -e "$messagebody" | $mymail -s "$SUBJECT" "$EMAIL" -- -f "$FROM"
+    fi
   fi
 
 else
